/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Employee;
import model.EmployeeHistory;

/**
 *
 * @author DKapoor
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    EmployeeHistory employeeHistory;
    public SearchJPanel(EmployeeHistory employeeHistory) {
        this.employeeHistory = employeeHistory;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSearchTextField = new javax.swing.JTextField();
        jNameBtn = new javax.swing.JButton();
        jEmailBtn = new javax.swing.JButton();
        jGenderTxtField = new javax.swing.JTextField();
        jNameLabel = new javax.swing.JLabel();
        jEmployeeIdLabel = new javax.swing.JLabel();
        jAgeLabel = new javax.swing.JLabel();
        jGenderLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTeamInfoTxtField = new javax.swing.JTextField();
        jNameTxtField = new javax.swing.JTextField();
        jPosTitleTxtField = new javax.swing.JTextField();
        jEmailAddressTxtField = new javax.swing.JTextField();
        jMobileNumberTxtField = new javax.swing.JTextField();
        jPhotoLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jEmpIdTxtField = new javax.swing.JTextField();
        jLevelTxtField = new javax.swing.JTextField();
        jAgeTxtField = new javax.swing.JTextField();
        jStartDateTxtField = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(800, 645));

        jLabel1.setText("Search");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search Employee Records");

        jSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchTextFieldActionPerformed(evt);
            }
        });

        jNameBtn.setText("Name");
        jNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameBtnActionPerformed(evt);
            }
        });

        jEmailBtn.setText("Email Adress");
        jEmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailBtnActionPerformed(evt);
            }
        });

        jNameLabel.setText("Name");

        jEmployeeIdLabel.setText("Employee ID");

        jAgeLabel.setText("Age");

        jGenderLabel.setText("Gender");

        jLabel6.setText("Start Date");

        jLabel7.setText("Level");

        jLabel8.setText("Team Information");

        jEmailAddressTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailAddressTxtFieldActionPerformed(evt);
            }
        });

        jPhotoLabel.setPreferredSize(new java.awt.Dimension(100, 250));

        jLabel9.setText("Position");

        jLabel10.setText("Email Address");

        jLabel11.setText("Mobile Number");

        jLabel12.setText("Photo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jGenderLabel)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jGenderTxtField)
                                            .addComponent(jPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jStartDateTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jAgeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jEmployeeIdLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jEmpIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTeamInfoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPosTitleTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEmailAddressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMobileNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLevelTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNameBtn)
                            .addComponent(jEmailBtn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jEmailBtn, jNameBtn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jAgeLabel, jEmployeeIdLabel, jGenderLabel, jLabel12, jLabel6, jNameLabel});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jEmpIdTxtField, jGenderTxtField, jNameTxtField});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel7, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jEmailAddressTxtField, jLevelTxtField, jMobileNumberTxtField, jPosTitleTxtField, jTeamInfoTxtField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jNameBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jEmailBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameLabel)
                    .addComponent(jNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLevelTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jEmployeeIdLabel)
                        .addComponent(jEmpIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTeamInfoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgeLabel)
                    .addComponent(jAgeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jPosTitleTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGenderLabel)
                    .addComponent(jGenderTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jEmailAddressTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel11)
                        .addComponent(jMobileNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jStartDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchTextFieldActionPerformed
    }//GEN-LAST:event_jSearchTextFieldActionPerformed

    private void jEmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailBtnActionPerformed
        if (jSearchTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter text in search field");
            jSearchTextField.requestFocus();
        }
        else{
            ArrayList empHistory = employeeHistory.getHistory();
            int i;
            int size = employeeHistory.getSize();
            for(i=0; i<size; i++){
                Employee emp = (Employee)empHistory.get(i);
                String email = emp.getEmailAddress();

                if (email.equalsIgnoreCase(jSearchTextField.getText())){
                    jNameTxtField.setText(emp.getName());
                    jEmpIdTxtField.setText(String.valueOf(emp.getEmployeeId()));
                    jStartDateTxtField.setDate(emp.getStartDate()); 
                    jAgeTxtField.setText(String.valueOf(emp.getAge()));
                    jLevelTxtField.setText(emp.getLevel());
                    jMobileNumberTxtField.setText(emp.getPhoneNumber());
                    jPosTitleTxtField.setText(emp.getPositionTitle());
                    jTeamInfoTxtField.setText(emp.getTeamInfo());
                    jGenderTxtField.setText(emp.getGender());
                    jEmailAddressTxtField.setText(emp.getEmailAddress());
                    jPhotoLabel.setIcon(emp.getPhoto());
                    
                    jNameTxtField.setEnabled(false);
                    jEmpIdTxtField.setEnabled(false);
                    jStartDateTxtField.setEnabled(false);
                    jAgeTxtField.setEnabled(false);
                    jLevelTxtField.setEnabled(false);
                    jMobileNumberTxtField.setEnabled(false);
                    jPosTitleTxtField.setEnabled(false);
                    jTeamInfoTxtField.setEnabled(false);
                    jGenderTxtField.setEnabled(false);
                    jEmailAddressTxtField.setEnabled(false);
                }
                else{
                    JOptionPane.showMessageDialog(this, "No record found for this email ID");
                    jNameTxtField.setText("");
                    jEmpIdTxtField.setText("");
                    jAgeTxtField.setText("");
                    jGenderTxtField.setText("");
                    jStartDateTxtField.setDate(null);
                    jLevelTxtField.setText("");
                    jTeamInfoTxtField.setText("");
                    jPosTitleTxtField.setText("");
                    jEmailAddressTxtField.setText("");
                    jMobileNumberTxtField.setText("");
                    jPhotoLabel.setIcon(null);
                }
            }
        }
    }//GEN-LAST:event_jEmailBtnActionPerformed

    private void jNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameBtnActionPerformed
        if (jSearchTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter text in search field");
            jSearchTextField.requestFocus();
        }
        else{
            ArrayList empHistory = employeeHistory.getHistory();
            int i;
            int size = employeeHistory.getSize();
            for(i=0; i<size; i++){
                Employee emp = (Employee)empHistory.get(i);
                String empId = emp.getName();

                if (empId.equalsIgnoreCase(jSearchTextField.getText())){
                    jNameTxtField.setText(emp.getName());
                    jEmpIdTxtField.setText(String.valueOf(emp.getEmployeeId()));
                    jStartDateTxtField.setDate(emp.getStartDate());
                    jAgeTxtField.setText(String.valueOf(emp.getAge()));
                    jLevelTxtField.setText(emp.getLevel());
                    jMobileNumberTxtField.setText(emp.getPhoneNumber());
                    jPosTitleTxtField.setText(emp.getPositionTitle());
                    jTeamInfoTxtField.setText(emp.getTeamInfo());
                    jGenderTxtField.setText(emp.getGender());
                    jEmailAddressTxtField.setText(emp.getEmailAddress());
                    jPhotoLabel.setIcon(emp.getPhoto());
                    
                    jNameTxtField.setEnabled(false);
                    jEmpIdTxtField.setEnabled(false);
                    jStartDateTxtField.setEnabled(false);
                    jAgeTxtField.setEnabled(false);
                    jLevelTxtField.setEnabled(false);
                    jMobileNumberTxtField.setEnabled(false);
                    jPosTitleTxtField.setEnabled(false);
                    jTeamInfoTxtField.setEnabled(false);
                    jGenderTxtField.setEnabled(false);
                    jEmailAddressTxtField.setEnabled(false);
                }
                else{
                    JOptionPane.showMessageDialog(this, "No record found for this name");
                    jNameTxtField.setText("");
                    jEmpIdTxtField.setText("");
                    jAgeTxtField.setText("");
                    jGenderTxtField.setText("");
                    jStartDateTxtField.setDate(null);
                    jLevelTxtField.setText("");
                    jTeamInfoTxtField.setText("");
                    jPosTitleTxtField.setText("");
                    jEmailAddressTxtField.setText("");
                    jMobileNumberTxtField.setText("");
                    jPhotoLabel.setIcon(null);
                }
            }
        }
    }//GEN-LAST:event_jNameBtnActionPerformed

    private void jEmailAddressTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailAddressTxtFieldActionPerformed
    }//GEN-LAST:event_jEmailAddressTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAgeLabel;
    private javax.swing.JTextField jAgeTxtField;
    private javax.swing.JTextField jEmailAddressTxtField;
    private javax.swing.JButton jEmailBtn;
    private javax.swing.JTextField jEmpIdTxtField;
    private javax.swing.JLabel jEmployeeIdLabel;
    private javax.swing.JLabel jGenderLabel;
    private javax.swing.JTextField jGenderTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLevelTxtField;
    private javax.swing.JTextField jMobileNumberTxtField;
    private javax.swing.JButton jNameBtn;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JTextField jNameTxtField;
    private javax.swing.JLabel jPhotoLabel;
    private javax.swing.JTextField jPosTitleTxtField;
    private javax.swing.JTextField jSearchTextField;
    private com.toedter.calendar.JDateChooser jStartDateTxtField;
    private javax.swing.JTextField jTeamInfoTxtField;
    // End of variables declaration//GEN-END:variables
}
